# -*- coding: utf-8 -*-
"""codigofinal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BxZNBS1XvqtNHKpamgWum2xsck0BU7Xc
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile codigofinal.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LinearRegression
# 
# st.write("# Predicción del costo de una actividad")
# st.image("actividades.png", caption="Predicción del costo de actividades registradas.")
# 
# st.header("Ingresa los datos de la actividad")
# 
# df_data = pd.read_csv("Registroprogramacion.csv")
# 
# df_data["Tipo"] = df_data["Tipo"].astype("category")
# df_data["Momento"] = df_data["Momento"].astype("category")
# 
# df_data["Tipo_code"] = df_data["Tipo"].cat.codes
# df_data["Momento_code"] = df_data["Momento"].cat.codes
# 
# X = df_data[["Presupuesto", "Tiempo invertido", "Tipo_code", "Momento_code", "No. de personas"]]
# y = df_data["Costo"]
# 
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)
# modelo = LinearRegression()
# modelo.fit(X_train, y_train)
# 
# def user_input():
#     Presupuesto = st.number_input("Presupuesto ($):", min_value=0, step=1)
#     Tiempo = st.number_input("Tiempo invertido (min):", min_value=0, step=1)
# 
#     Tipo = st.selectbox("Tipo de actividad:", df_data["Tipo"].unique())
#     Momento = st.selectbox("Momento del día:", df_data["Momento"].unique())
# 
#     Personas = st.number_input("Número de personas:", min_value=1, step=1)
# 
#     # Convertir categorías a códigos para la predicción
#     Tipo_code = df_data["Tipo"].cat.categories.get_loc(Tipo)
#     Momento_code = df_data["Momento"].cat.categories.get_loc(Momento)
# 
#     data = pd.DataFrame({
#         "Presupuesto": [Presupuesto],
#         "Tiempo invertido": [Tiempo],
#         "Tipo_code": [Tipo_code],
#         "Momento_code": [Momento_code],
#         "No. de personas": [Personas]
#     })
# 
#     return data
# 
# input_data = user_input()
# 
# prediccion = modelo.predict(input_data)[0]
# 
# st.subheader("Costo estimado de la actividad")
# st.write(f"El costo estimado es: **${prediccion:.2f}**")